{{- $fullName := include "fullname" . -}}
{{- if .Values.secrets.enabled }}

{{- if ne false .Values.secrets.env }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-secret
  labels:
  {{- include "labels" . | nindent 4 }}
  {{- if .Values.secrets.annotations }}
  annotations:
  {{- toYaml .Values.secrets.annotations | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval | default "30m" }}
  secretStoreRef:
    kind: {{ .Values.secrets.kind | default "ClusterSecretStore" }}
    name: {{ .Values.secrets.backend }}
  target:
    name: {{ $fullName }}-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.projectNamespace }}/{{ $fullName }}/env/{{ .Values.env }}

{{- if .Values.secrets.common }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-common
  labels:
  {{- include "labels" . | nindent 4 }}
  {{- if .Values.secrets.annotations }}
  annotations:
  {{- toYaml .Values.secrets.annotations | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval | default "30m" }}
  secretStoreRef:
    kind: {{ .Values.secrets.kind | default "ClusterSecretStore" }}
    name: {{ .Values.secrets.backend }}
  target:
    name: {{ $fullName }}-common
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.projectNamespace }}/common/env/{{ .Values.env }}
{{- end }}
{{- end }}

{{- range .Values.secrets.files }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-{{ .name | replace "." "-" }}
  labels:
  {{- include "labels" $ | nindent 4 }}
  {{- if $.Values.secrets.annotations }}
  annotations:
  {{- toYaml $.Values.secrets.annotations | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ $.Values.secrets.refreshInterval | default "30m" }}
  secretStoreRef:
    kind: {{ $.Values.secrets.kind | default "ClusterSecretStore" }}
    name: {{ $.Values.secrets.backend }}
  target:
    name: {{ $fullName }}-{{ .name | replace "." "-" }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ $.Values.secrets.projectNamespace }}/{{ $fullName }}/files/{{ $.Values.env }}
        property: {{ .name }}
{{- end }}

{{- range .Values.secrets.commonFiles }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-{{ .name | replace "." "-" }}-common-files
  labels:
  {{- include "labels" $ | nindent 4 }}
  {{- if $.Values.secrets.annotations }}
  annotations:
  {{- toYaml $.Values.secrets.annotations | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ $.Values.secrets.refreshInterval | default "30m" }}
  secretStoreRef:
    kind: {{ $.Values.secrets.kind | default "ClusterSecretStore" }}
    name: {{ $.Values.secrets.backend }}
  target:
    name: {{ $fullName }}-{{ .name | replace "." "-" }}-common-files
    creationPolicy: Owner
  data:
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ $.Values.secrets.projectNamespace }}/common/files/{{ $.Values.env }}
        property: {{ .name }}
{{- end }}
{{- end }}

{{- if .Values.ingress }}
{{- range $ingr := .Values.ingress }}
{{- range $host := $ingr.hosts }}
{{- if and ($host.tls) (not $host.tlsSecret) }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $host.host | replace "." "-" }}-tls
  labels:
  {{- include "labels" $ | nindent 4 }}
  {{- if $.Values.secrets.annotations }}
  annotations:
  {{- toYaml $.Values.secrets.annotations | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: 168h
  secretStoreRef:
    kind: {{ $.Values.secrets.kind | default "ClusterSecretStore" }}
    name: {{ $.Values.secrets.tls.backend | default $.Values.secrets.backend }}
  target:
    name: {{ $host.host | replace "." "-"  }}-tls
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: {{ `"{{ .crt | fromJson | values | first }}"` }}
        tls.key: {{ `"{{ .key | fromJson | values | first }}"` }}
  data:
  {{- if $host.tls.common }}
    - secretKey: crt
      remoteRef:
        key: common/tls/crt
    - secretKey: key
      remoteRef:
        key: common/tls/key
  {{ else }}
    - secretKey: crt
      remoteRef:
        key: {{ printf "%s/tls/crt" ($host.tls.customPath | default $.Values.secrets.projectNamespace) | quote }}
    - secretKey: key
      remoteRef:
        key: {{ printf "%s/tls/key" ($host.tls.customPath | default $.Values.secrets.projectNamespace) | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}